title: Arquip√©lago Arquitetos
description: Portfolio de Arquitetura
url: ""
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sass-converter

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  sass_dir: _sass


